#    ______    _____   ____    __  ___
#   / ____/   / /   | / __ \  /  |/  /
#  / /   __  / / /| |/ / / / / /|_/ /  By jonagamerpro1234
# / /___/ /_/ / ___ / /_/ / / /  / /   Version ${project.version}
# \____/\____/_/  |_\___\_\/_/  /_/    Thanks for using CustomJoinAndQuitMessage <3
#
# ● A simple plugin for personalization of the join and quit messages and more...
#
# ● Spigot: https://www.spigotmc.org/resources/custom-join-and-quit-message.57006/
# ● Modrinth: https://modrinth.com/plugin/customjoinandquitmessages
# ● Discord: https://discord.gg/c5GhQDQCK5
# ● Issue Tracker: https://github.com/jonagamerpro1234/CustomJoinAndQuitMessages/issues
# ● Plugin Statistics: https://bstats.org/plugin/bukkit/CustomJoinAndQuitMessages/6318

# | Settings |
Settings:

  # Shows you important information about the plugin loading
  Debug: true

  # DevMode this mode show dev command and more functions
  DevMode: true

  # You can use the available languages of the plugin, or you can add your own translations [ Default = en_US ]
  Lang: en_US

  # This function lets you know if there is a plugin update [Does not disable console messages]
  Update:

    # Here you can enable or disable this feature
    Enabled: true

    # You will get the updates from [spigot | gitHub] what is the difference, here below is the explanation of why
    # |Spigot| Get only released updates, and you won't receive beta notifications
    # |Modrinth| Get only the released and beta updates, and you will be able to receive notifications of both versions
    # |GitHub| Get only the released and beta updates, and you will be able to receive notifications of both versions
    GetFromUpdate: spigot

#
Database:

  Enabled: false

  Host: "localhost"

  Port: 3306

  Database: "devplugin"

  User: "root"

  Password: ""

# | Hooks | Work in progress
Hooks:

  # Here you can configure everything related to LuckPerms and or deactivate or activate functions
  LuckPerms:

    # Here you can enable or disable this feature
    Enabled: true

    # This function allows the plugin to detect if the player has changed rank in a period of time defined in the [Tick] section
    AutoUpdateGroup:

      # Here you can enable or disable this feature
      Enabled: true

      # Delay time for the group update task to start
      Delay: 0

      # Here you can define the time that the actions are automatically executed [Default = 600], 600 tick = 30 sec
      Tick: 600

  # Here you can define the discord channel where the messages from minecraft to discord are seen
  DiscordSVR:

    # Here you can enable or disable this feature
    Enabled: true

    # Here is the id of the channel used for the chat
    Channel-Id: "none"

  # Here you can change the settings of each implementation that works with EssentialsX
  EssentialsX:

    # Here you can enable or disable this feature
    Enabled: true

    # This allows you to join or quit the server without the message being shown to other players.
    HidePlayerIsVanish: true

    #
    DisableJoinQuitSoundsInVanish: true

    # Here you can define the discord channel where the messages from minecraft to discord are seen
    # (!) You need to have the [Essentials Discord] plugin for it to work
    EssentialsDiscord:

      # Here you can enable or disable this feature
      Enabled: true

      # Here is the id of the channel used for the chat
      Channel-Id: "none"

      # It will use the channel defined in the EssentialsDiscord plugin configuration and ignore the Channel-Id of CustomJoinAndMessages
      UseDefaultChannel: false

# | ChatFormat |
# Here you can customize the player's entry and exit messages, and you can also customize the messages with various functions
# (!) For group customization you need to change the type to [ group ]
ChatFormat:

  # Here you can enable or disable the chat to be seen in the console
  ShowChatInConsole: true

  # Here you can configure the type of the format which are
  # |normal| It is used for the general customization of all players' input and output messages, this does not allow the use of group functions.
  # |group| It is used for customization by groups and disables general customization and allows better customization for each group
  # (!) It is necessary to have LuckPerms to use group customization
  Type: normal

  # | Join |
  Join:

    # Here you can enable or disable this feature
    Enabled: true

    # Here you can define the input message
    Format: "&e[&a+&e] &3{player} &7has joined the server"

    #[Coming Soon]
    JoinMessageDelay: 0

    # In this section, you can configure the title of the join
    Title-Settings:

      # Here you can enable or disable this feature
      Enabled: true

      # here you can set the title text
      Title: "<aqua>Welcome to the server"

      # here you can set the subtitle text
      SubTitle: "{player}"

      # here you can set the input time of the title
      FadeIn: 20

      # here you can set how long the title stays
      Stay: 40

      # here you can set the title output time
      FadeOut: 20

    # In this section, you can configure the Actionbar of the join
    Actionbar:

      # Here you can enable or disable this feature
      Enabled: true

      #[Coming Soon]
      Delay: 0

      # here you can set the message that appears in the action bar
      Format: "<gradient:#8afff5:#ff1430>Welcome to server {player}</gradient>"

    # |Sound| In this section you can configure the sound of the join
    # |Sound list: https://www.spigotmc.org/wiki/cc-sounds-list/
    Sound:

      # Here you can enable or disable this feature
      Enabled: true

      # When active, the sound will be sent to all players connected to the server
      SendToAll: true

      # This is the name of the sound you will hear when it is mentioned to you in chat
      Name: "BLOCK_NOTE_BLOCK_PLING"

      # This is the volume of the sound that you will hear when the chat mentions it
      Volume: 10

      # This is the pitch of the sound that you will hear when mentioned in the chat
      Pitch: 1

  # | First Join |
  First-Join:

    # Here you can enable or disable this feature
    Enabled: true

    #
    Format: "&3Welcome to the server, we hope you enjoy your time here and have a good time"

    #[Coming Soon]
    FirstJoinMessageDelay: 0

    # In this section, you can configure the title of the join
    Title-Settings:

      # Here you can enable or disable this feature
      Enabled: true

      # here you can set the title text
      Title: ""

      # here you can set the subtitle text
      SubTitle: ""

      # here you can set the input time of the title
      FadeIn: 20

      # here you can set how long the title stays
      Stay: 40

      # here you can set the title output time
      FadeOut: 20

    # In this section, you can configure the Actionbar of the first join
    Actionbar:

      # Here you can enable or disable this feature
      Enabled: true

      #[Coming Soon]
      Delay: 0

      # here you can set the message that appears in the action bar
      Format: "<red>Welcome to the &bserver"

    # |Sound| In this section you can configure the sound of the first join
    # |Sound list: https://www.spigotmc.org/wiki/cc-sounds-list/
    Sound:

      # Here you can enable or disable this feature
      Enabled: true

      # When active, the sound will be sent to all players connected to the server
      SendToAll: true

      # This is the name of the sound you will hear when it is mentioned to you in chat
      Name: "BLOCK_NOTE_BLOCK_PLING"

      # This is the volume of the sound that you will hear when the chat mentions it
      Volume: 10

      # This is the pitch of the sound that you will hear when mentioned in the chat
      Pitch: 1

  # | Quit |
  Quit:

    # Here you can enable or disable this feature
    Enabled: true

    # Here you can define the output message
    Format: "&e[&c-&e] &3{player} &7has left the server"

    #
    Title-Settings:

      # Here you can enable or disable this feature
      Enabled: true

      # here you can set the title text
      Title: ""

      # here you can set the subtitle text
      SubTitle: ""

      # here you can set the input time of the title
      FadeIn: 20

      # here you can set how long the title stays
      Stay: 40

      # here you can set the title output time
      FadeOut: 20

    # In this section, you can configure the Actionbar of the quit
    Actionbar:

      # Here you can enable or disable this feature
      Enabled: true

      #[Coming Soon]
      Delay: 0

      # here you can set the message that appears in the action bar
      Format: "<red>Welcome to the &bserver"

    # |Sound| In this section you can configure the sound of the quit
    # |Sound list: https://www.spigotmc.org/wiki/cc-sounds-list/
    Sound:

      # Here you can enable or disable this feature
      Enabled: true

      # [Experimental] When active, the sound will be sent to all players connected to the server
      SendToAll: true

      # This is the name of the sound you will hear when it is mentioned to you in chat
      Name: "BLOCK_NOTE_BLOCK_PLING"

      # This is the volume of the sound that you will hear when the chat mentions it
      Volume: 10

      # This is the pitch of the sound that you will hear when mentioned in the chat
      Pitch: 1

# |Welcome|
Welcome:

  # Here you can enable or disable this feature
  Enabled: true

  # Allows you to use one welcome message per group and disable the general welcome message
  UseWelcomePerGroup: false

  #[Coming Soon]
  Delay: 0

  # Here you can set your own welcome message when entering
  Text:
    - '<gradient:#8200FC:#00FC95>&m=========================================</gradient>&r'
    - '{0}'
    - '&e> &7Welcome To The Server &b<name>'
    - '{0}'
    - '&e> <red>Shop: shop-example.com'
    - '&e> &7Use &b/skin to put on a skin'
    - '{0}'
    - '<gradient:#8200FC:#00FC95>&m=========================================</gradient>&r'

# I would not change anything
File-Version: 5

# |> This is the end of the configuration... [-_-] more things coming soon
#
# | Config File |
# | Version 1.8 |
#